### ISSUE TITLE
App Icon notification reappearing

### ISSUE THREAD

**Issue by GerRudi** [milesmcc/LibreNews-Android#13]
I received the notification with the app icon feedback link several times within a few minutes. 
(My app icon is fine)

Even after clicking on it, it still keeps reappearing after a few minutes (only 1 notification at a time)
Using https://librenews.io/api

**Comment by chiragkolani** [comment]
I have same issue. New feedback notification every 5 minutes

**Comment by GerRudi** [comment]
Update: Issue still exists and it's rather annoying. :/

**Comment by milesmcc** [comment]
Try uninstalling and reinstalling the app. Let me know if that helps...

**Comment by GerRudi** [comment]
Sorry for the late response. 
After I reinstalled it, I couldn't check whether it was working or not as didn't receive any notification at all (this might have been my firewall though, I'm not 100% sure). In the meantime, I flashed a new ROM and the issue is now gone - unfortunately, I can't provide any more information about this issue other than that it's not appearing anymore.

**Comment by milesmcc** [comment]
Ok. Let me know if it reappears. In the meantime, I am going to close the issue. Thanks for bringing this to my attention.
