### ISSUE TITLE
Notifications not working on Android 8.0 (Oreo)

### ISSUE THREAD

**Issue by milesmcc** [milesmcc/LibreNews-Android#14]
This *includes* debug notifications, which are also not fired.

**Comment by flocke** [comment]
Got the same thing on my Nexus 5X since the Oreo update. I'm gonna try to get a logcat for you as soon as I am back home (Sunday).

**Comment by milesmcc** [comment]
Fixed in the latest release :)

**Comment by flocke** [comment]
Sounds good, will test it as soon as F-Droid updates the package ;)

**Comment by milesmcc** [comment]
This is fixed in 72bf7a0.
