### ISSUE TITLE
Google Play Store

### ISSUE THREAD

**Issue by Niquarl** [milesmcc/LibreNews-Android#29]
The Google Play Store link seems to be broken. Is that normal, has the app been taken down from the Play Store?

**Comment by milesmcc** [comment]
You're right — I took the app off of Google Play for a few reasons (which I'll list below), but didn't remove the link in README.md. This is fixed as of b9e33b1.

Here are the reasons I removed the app from Google Play:
* Nearly 95% of downloads came through F-Droid.
* If you want LibreNews on your non-F-Droid Android device, you can just subscribe to push notifications from LibreNews at LibreNews.io. (This solution does _not_ require you to download any proprietary code)

Thanks for bringing this to my attention.
