### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by mueller-ma** [milesmcc/LibreNews-Android#3]
In the apps main menu there is zero information about librenews

**Comment by milesmcc** [comment]
I've pushed a fix: https://github.com/milesmcc/LibreNews-Android/commit/6c2415fe3d1c628d9e72d7ac29e6c4e98393f287

**Comment by milesmcc** [comment]
I've added a button. If you have a better fix (possibly a main flash view page), please do submit a PR, but in the meantime I've pushed out an update (v1.2, which also adds wifi-only support).

**Comment by mueller-ma** [comment]
I will see when its live on fdroid

**Comment by milesmcc** [comment]
It should be live within the next few days. Thanks for your contributions!
