### ISSUE TITLE
Disable announcements by default?

### ISSUE THREAD

**Issue by mueller-ma** [milesmcc/LibreNews-Android#7]
Mostly LibreNews presents itself as a breaking news notification service. But for that the default settings with announcements on are IMO a little bit spammy.

**Comment by mueller-ma** [comment]
I just see that all the notifications from today are breaking news. Maybe we should correct the number in the strings.xml to 10 instead of 3

**Comment by milesmcc** [comment]
Most days, it tends to be about 5... I'd certainly consider a change, though I believe 3 is appropriate for most days. We can see how the rest of the week pans out.

As for disabling announcements by default, I'm generally against that. I don't think it's spammy, as I have yet to ever send out a LibreNews announcement, and I only plan to should I discover a major security vulnerability. I think that as long as the user has the ability to disable them, it is fine. Do you agree or disagree?

**Comment by mueller-ma** [comment]
You're right. I just didn't know what announcement means in this case.
Sometime the news are not that breaking to get a notification, e.g. "LA wants to host olympia". Have you considered another news provider or aren't you disturbed by such news?
